language: perl
perl:
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - "cpanm --installdeps ."
    - "cpanm Moose"
    - "cpanm Date::Utility" 
    - "cpanm Data::Chronicle::Reader"
    - "cpanm Data::Chronicle::Writer"
    - "cpanm Data::Chronicle::Mock"
    - "cpanm YAML::XS"
    - "cpanm File::ShareDir"
    - "cpanm Test::Manifest"
    - "cpanm Test::MockModule"
    - "cpanm Test::MockObject::Extends"
    - "cpanm Date::Utility" 
    - "cpanm Memoize"
    - "cpanm Memoize::HashKey::Ignore"
    - "cpanm Time::Duration::Concise"
script:
  perl Makefile.PL && RELEASE_TESTING=1 make test
